<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["name"=>"Afghanistan", "code"=>"AF", "phonecode"=>"+93"],
            ["name"=>"Åland Islands", "code"=>"AX", "phonecode"=>"+358"],
            ["name"=>"Albania", "code"=>"AL", "phonecode"=>"+355"],
            ["name"=>"Algeria", "code"=>"DZ", "phonecode"=>"+213"],
            ["name"=>"American Samoa", "code"=>"AS", "phonecode"=>"+1684"],
            ["name"=>"Andorra", "code"=>"AD", "phonecode"=>"+376"],
            ["name"=>"Angola", "code"=>"AO", "phonecode"=>"+244"],
            ["name"=>"Anguilla", "code"=>"AI", "phonecode"=>"+1264"],
            ["name"=>"Antarctica", "code"=>"AQ", "phonecode"=>"+672"],
            ["name"=>"Antigua and Barbuda", "code"=>"AG", "phonecode"=>"+1268"],
            ["name"=>"Argentina", "code"=>"AR", "phonecode"=>"+54"],
            ["name"=>"Armenia", "code"=>"AM", "phonecode"=>"+374"],
            ["name"=>"Aruba", "code"=>"AW", "phonecode"=>"+297"],
            ["name"=>"Australia", "code"=>"AU", "phonecode"=>"+61"],
            ["name"=>"Austria", "code"=>"AT", "phonecode"=>"+43"],
            ["name"=>"Azerbaijan", "code"=>"AZ", "phonecode"=>"+994"],
            ["name"=>"Bahamas", "code"=>"BS", "phonecode"=>"+1242"],
            ["name"=>"Bahrain", "code"=>"BH", "phonecode"=>"+973"],
            ["name"=>"Bangladesh", "code"=>"BD", "phonecode"=>"+880"],
            ["name"=>"Barbados", "code"=>"BB", "phonecode"=>"+1246"],
            ["name"=>"Belarus", "code"=>"BY", "phonecode"=>"+375"],
            ["name"=>"Belgium", "code"=>"BE", "phonecode"=>"+32"],
            ["name"=>"Belize", "code"=>"BZ", "phonecode"=>"+501"],
            ["name"=>"Benin", "code"=>"BJ", "phonecode"=>"+229"],
            ["name"=>"Bermuda", "code"=>"BM", "phonecode"=>"+1441"],
            ["name"=>"Bhutan", "code"=>"BT", "phonecode"=>"+975"],
            ["name"=>"Bolivia, Plurinational State of", "code"=>"BO", "phonecode"=>"+591"],
            ["name"=>"Bonaire, Sint Eustatius and Saba", "code"=>"BQ", "phonecode"=>"+599"],
            ["name"=>"Bosnia and Herzegovina", "code"=>"BA", "phonecode"=>"+387"],
            ["name"=>"Botswana", "code"=>"BW", "phonecode"=>"+267"],
            ["name"=>"Bouvet Island", "code"=>"BV", "phonecode"=>"+0"],
            ["name"=>"Brazil", "code"=>"BR", "phonecode"=>"+55"],
            ["name"=>"British Indian Ocean Territory", "code"=>"IO", "phonecode"=>"+246"],
            ["name"=>"Brunei Darussalam", "code"=>"BN", "phonecode"=>"+673"],
            ["name"=>"Bulgaria", "code"=>"BG", "phonecode"=>"+359"],
            ["name"=>"Burkina Faso", "code"=>"BF", "phonecode"=>"+226"],
            ["name"=>"Burundi", "code"=>"BI", "phonecode"=>"+257"],
            ["name"=>"Cambodia", "code"=>"KH", "phonecode"=>"+855"],
            ["name"=>"Cameroon", "code"=>"CM", "phonecode"=>"+237"],
            ["name"=>"Canada", "code"=>"CA", "phonecode"=>"+1"],
            ["name"=>"Cape Verde", "code"=>"CV", "phonecode"=>"+238"],
            ["name"=>"Cayman Islands", "code"=>"KY", "phonecode"=>"+1345"],
            ["name"=>"Central African Republic", "code"=>"CF", "phonecode"=>"+236"],
            ["name"=>"Chad", "code"=>"TD", "phonecode"=>"+235"],
            ["name"=>"Chile", "code"=>"CL", "phonecode"=>"+56"],
            ["name"=>"China", "code"=>"CN", "phonecode"=>"+86"],
            ["name"=>"Christmas Island", "code"=>"CX", "phonecode"=>"+61"],
            ["name"=>"Cocos (Keeling) Islands", "code"=>"CC", "phonecode"=>"+672"],
            ["name"=>"Colombia", "code"=>"CO", "phonecode"=>"+57"],
            ["name"=>"Comoros", "code"=>"KM", "phonecode"=>"+269"],
            ["name"=>"Congo", "code"=>"CG", "phonecode"=>"+242"],
            ["name"=>"Congo, the Democratic Republic of the", "code"=>"CD", "phonecode"=>"+242"],
            ["name"=>"Cook Islands", "code"=>"CK", "phonecode"=>"+682"],
            ["name"=>"Costa Rica", "code"=>"CR", "phonecode"=>"+506"],
            ["name"=>"Côte d'Ivoire", "code"=>"CI", "phonecode"=>"+225"],
            ["name"=>"Croatia", "code"=>"HR", "phonecode"=>"+385"],
            ["name"=>"Cuba", "code"=>"CU", "phonecode"=>"+53"],
            ["name"=>"Curaçao", "code"=>"CW", "phonecode"=>"+599"],
            ["name"=>"Cyprus", "code"=>"CY", "phonecode"=>"+357"],
            ["name"=>"Czech Republic", "code"=>"CZ", "phonecode"=>"+420"],
            ["name"=>"Denmark", "code"=>"DK", "phonecode"=>"+45"],
            ["name"=>"Djibouti", "code"=>"DJ", "phonecode"=>"+253"],
            ["name"=>"Dominica", "code"=>"DM", "phonecode"=>"+1767"],
            ["name"=>"Dominican Republic", "code"=>"DO", "phonecode"=>"+1"],
            ["name"=>"Ecuador", "code"=>"EC", "phonecode"=>"+593"],
            ["name"=>"Egypt", "code"=>"EG", "phonecode"=>"+20"],
            ["name"=>"El Salvador", "code"=>"SV", "phonecode"=>"+503"],
            ["name"=>"Equatorial Guinea", "code"=>"GQ", "phonecode"=>"+240"],
            ["name"=>"Eritrea", "code"=>"ER", "phonecode"=>"+291"],
            ["name"=>"Estonia", "code"=>"EE", "phonecode"=>"+372"],
            ["name"=>"Ethiopia", "code"=>"ET", "phonecode"=>"+251"],
            ["name"=>"Falkland Islands (Malvinas)", "code"=>"FK", "phonecode"=>"+500"],
            ["name"=>"Faroe Islands", "code"=>"FO", "phonecode"=>"+298"],
            ["name"=>"Fiji", "code"=>"FJ", "phonecode"=>"+679"],
            ["name"=>"Finland", "code"=>"FI", "phonecode"=>"+358"],
            ["name"=>"France", "code"=>"FR", "phonecode"=>"+33"],
            ["name"=>"French Guiana", "code"=>"GF", "phonecode"=>"+594"],
            ["name"=>"French Polynesia", "code"=>"PF", "phonecode"=>"+689"],
            ["name"=>"French Southern Territories", "code"=>"TF", "phonecode"=>"+0"],
            ["name"=>"Gabon", "code"=>"GA", "phonecode"=>"+241"],
            ["name"=>"Gambia", "code"=>"GM", "phonecode"=>"+220"],
            ["name"=>"Georgia", "code"=>"GE", "phonecode"=>"+995"],
            ["name"=>"Germany", "code"=>"DE", "phonecode"=>"+49"],
            ["name"=>"Ghana", "code"=>"GH", "phonecode"=>"+233"],
            ["name"=>"Gibraltar", "code"=>"GI", "phonecode"=>"+350"],
            ["name"=>"Greece", "code"=>"GR", "phonecode"=>"+30"],
            ["name"=>"Greenland", "code"=>"GL", "phonecode"=>"+299"],
            ["name"=>"Grenada", "code"=>"GD", "phonecode"=>"+1473"],
            ["name"=>"Guadeloupe", "code"=>"GP", "phonecode"=>"+590"],
            ["name"=>"Guam", "code"=>"GU", "phonecode"=>"+1671"],
            ["name"=>"Guatemala", "code"=>"GT", "phonecode"=>"+502"],
            ["name"=>"Guernsey", "code"=>"GG", "phonecode"=>"+44"],
            ["name"=>"Guinea", "code"=>"GN", "phonecode"=>"+224"],
            ["name"=>"Guinea-Bissau", "code"=>"GW", "phonecode"=>"+245"],
            ["name"=>"Guyana", "code"=>"GY", "phonecode"=>"+592"],
            ["name"=>"Haiti", "code"=>"HT", "phonecode"=>"+509"],
            ["name"=>"Heard Island and McDonald Mcdonald Islands", "code"=>"HM", "phonecode"=>"+0"],
            ["name"=>"Holy See (Vatican City State)", "code"=>"VA", "phonecode"=>"+39"],
            ["name"=>"Honduras", "code"=>"HN", "phonecode"=>"+504"],
            ["name"=>"Hong Kong", "code"=>"HK", "phonecode"=>"+852"],
            ["name"=>"Hungary", "code"=>"HU", "phonecode"=>"+36"],
            ["name"=>"Iceland", "code"=>"IS", "phonecode"=>"+354"],
            ["name"=>"India", "code"=>"IN", "phonecode"=>"+91"],
            ["name"=>"Indonesia", "code"=>"ID", "phonecode"=>"+62"],
            ["name"=>"Iran, Islamic Republic of", "code"=>"IR", "phonecode"=>"+98"],
            ["name"=>"Iraq", "code"=>"IQ", "phonecode"=>"+964"],
            ["name"=>"Ireland", "code"=>"IE", "phonecode"=>"+353"],
            ["name"=>"Isle of Man", "code"=>"IM", "phonecode"=>"+44"],
            ["name"=>"Israel", "code"=>"IL", "phonecode"=>"+972"],
            ["name"=>"Italy", "code"=>"IT", "phonecode"=>"+39"],
            ["name"=>"Jamaica", "code"=>"JM", "phonecode"=>"+1876"],
            ["name"=>"Japan", "code"=>"JP", "phonecode"=>"+81"],
            ["name"=>"Jersey", "code"=>"JE", "phonecode"=>"+44"],
            ["name"=>"Jordan", "code"=>"JO", "phonecode"=>"+962"],
            ["name"=>"Kazakhstan", "code"=>"KZ", "phonecode"=>"+7"],
            ["name"=>"Kenya", "code"=>"KE", "phonecode"=>"+254"],
            ["name"=>"Kiribati", "code"=>"KI", "phonecode"=>"+686"],
            ["name"=>"Korea, Democratic People's Republic of", "code"=>"KP", "phonecode"=>"+850"],
            ["name"=>"Korea, Republic of", "code"=>"KR", "phonecode"=>"+82"],
            ["name"=>"Kuwait", "code"=>"KW", "phonecode"=>"+965"],
            ["name"=>"Kyrgyzstan", "code"=>"KG", "phonecode"=>"+996"],
            ["name"=>"Lao People's Democratic Republic", "code"=>"LA", "phonecode"=>"+856"],
            ["name"=>"Latvia", "code"=>"LV", "phonecode"=>"+371"],
            ["name"=>"Lebanon", "code"=>"LB", "phonecode"=>"+961"],
            ["name"=>"Lesotho", "code"=>"LS", "phonecode"=>"+266"],
            ["name"=>"Liberia", "code"=>"LR", "phonecode"=>"+231"],
            ["name"=>"Libya", "code"=>"LY", "phonecode"=>"+218"],
            ["name"=>"Liechtenstein", "code"=>"LI", "phonecode"=>"+423"],
            ["name"=>"Lithuania", "code"=>"LT", "phonecode"=>"+370"],
            ["name"=>"Luxembourg", "code"=>"LU", "phonecode"=>"+352"],
            ["name"=>"Macao", "code"=>"MO", "phonecode"=>"+853"],
            ["name"=>"Macedonia, the Former Yugoslav Republic of", "code"=>"MK", "phonecode"=>"+389"],
            ["name"=>"Madagascar", "code"=>"MG", "phonecode"=>"+261"],
            ["name"=>"Malawi", "code"=>"MW", "phonecode"=>"+265"],
            ["name"=>"Malaysia", "code"=>"MY", "phonecode"=>"+60"],
            ["name"=>"Maldives", "code"=>"MV", "phonecode"=>"+960"],
            ["name"=>"Mali", "code"=>"ML", "phonecode"=>"+223"],
            ["name"=>"Malta", "code"=>"MT", "phonecode"=>"+356"],
            ["name"=>"Marshall Islands", "code"=>"MH", "phonecode"=>"+692"],
            ["name"=>"Martinique", "code"=>"MQ", "phonecode"=>"+596"],
            ["name"=>"Mauritania", "code"=>"MR", "phonecode"=>"+222"],
            ["name"=>"Mauritius", "code"=>"MU", "phonecode"=>"+230"],
            ["name"=>"Mayotte", "code"=>"YT", "phonecode"=>"+269"],
            ["name"=>"Mexico", "code"=>"MX", "phonecode"=>"+52"],
            ["name"=>"Micronesia, Federated States of", "code"=>"FM", "phonecode"=>"+691"],
            ["name"=>"Moldova, Republic of", "code"=>"MD", "phonecode"=>"+373"],
            ["name"=>"Monaco", "code"=>"MC", "phonecode"=>"+377"],
            ["name"=>"Mongolia", "code"=>"MN", "phonecode"=>"+976"],
            ["name"=>"Montenegro", "code"=>"ME", "phonecode"=>"+382"],
            ["name"=>"Montserrat", "code"=>"MS", "phonecode"=>"+1664"],
            ["name"=>"Morocco", "code"=>"MA", "phonecode"=>"+212"],
            ["name"=>"Mozambique", "code"=>"MZ", "phonecode"=>"+258"],
            ["name"=>"Myanmar", "code"=>"MM", "phonecode"=>"+95"],
            ["name"=>"Namibia", "code"=>"NA", "phonecode"=>"+264"],
            ["name"=>"Nauru", "code"=>"NR", "phonecode"=>"+674"],
            ["name"=>"Nepal", "code"=>"NP", "phonecode"=>"+977"],
            ["name"=>"Netherlands", "code"=>"NL", "phonecode"=>"+31"],
            ["name"=>"New Caledonia", "code"=>"NC", "phonecode"=>"+687"],
            ["name"=>"New Zealand", "code"=>"NZ", "phonecode"=>"+64"],
            ["name"=>"Nicaragua", "code"=>"NI", "phonecode"=>"+505"],
            ["name"=>"Niger", "code"=>"NE", "phonecode"=>"+227"],
            ["name"=>"Nigeria", "code"=>"NG", "phonecode"=>"+234"],
            ["name"=>"Niue", "code"=>"NU", "phonecode"=>"+683"],
            ["name"=>"Norfolk Island", "code"=>"NF", "phonecode"=>"+672"],
            ["name"=>"Northern Mariana Islands", "code"=>"MP", "phonecode"=>"+1670"],
            ["name"=>"Norway", "code"=>"NO", "phonecode"=>"+47"],
            ["name"=>"Oman", "code"=>"OM", "phonecode"=>"+968"],
            ["name"=>"Pakistan", "code"=>"PK", "phonecode"=>"+92"],
            ["name"=>"Palau", "code"=>"PW", "phonecode"=>"+680"],
            ["name"=>"Palestine, State of", "code"=>"PS", "phonecode"=>"+970"],
            ["name"=>"Panama", "code"=>"PA", "phonecode"=>"+507"],
            ["name"=>"Papua New Guinea", "code"=>"PG", "phonecode"=>"+675"],
            ["name"=>"Paraguay", "code"=>"PY", "phonecode"=>"+595"],
            ["name"=>"Peru", "code"=>"PE", "phonecode"=>"+51"],
            ["name"=>"Philippines", "code"=>"PH", "phonecode"=>"+63"],
            ["name"=>"Pitcairn", "code"=>"PN", "phonecode"=>"+64"],
            ["name"=>"Poland", "code"=>"PL", "phonecode"=>"+48"],
            ["name"=>"Portugal", "code"=>"PT", "phonecode"=>"+351"],
            ["name"=>"Puerto Rico", "code"=>"PR", "phonecode"=>"+1787"],
            ["name"=>"Qatar", "code"=>"QA", "phonecode"=>"+974"],
            ["name"=>"Réunion", "code"=>"RE", "phonecode"=>"+262"],
            ["name"=>"Romania", "code"=>"RO", "phonecode"=>"+40"],
            ["name"=>"Russian Federation", "code"=>"RU", "phonecode"=>"+7"],
            ["name"=>"Rwanda", "code"=>"RW", "phonecode"=>"+250"],
            ["name"=>"Saint Barthélemy", "code"=>"BL", "phonecode"=>"+590"],
            ["name"=>"Saint Helena, Ascension and Tristan da Cunha", "code"=>"SH", "phonecode"=>"+290"],
            ["name"=>"Saint Kitts and Nevis", "code"=>"KN", "phonecode"=>"+1869"],
            ["name"=>"Saint Lucia", "code"=>"LC", "phonecode"=>"+1758"],
            ["name"=>"Saint Martin (French part)", "code"=>"MF", "phonecode"=>"+590"],
            ["name"=>"Saint Pierre and Miquelon", "code"=>"PM", "phonecode"=>"+508"],
            ["name"=>"Saint Vincent and the Grenadines", "code"=>"VC", "phonecode"=>"+1784"],
            ["name"=>"Samoa", "code"=>"WS", "phonecode"=>"+684"],
            ["name"=>"San Marino", "code"=>"SM", "phonecode"=>"+378"],
            ["name"=>"Sao Tome and Principe", "code"=>"ST", "phonecode"=>"+239"],
            ["name"=>"Saudi Arabia", "code"=>"SA", "phonecode"=>"+966"],
            ["name"=>"Senegal", "code"=>"SN", "phonecode"=>"+221"],
            ["name"=>"Serbia", "code"=>"RS", "phonecode"=>"+381"],
            ["name"=>"Seychelles", "code"=>"SC", "phonecode"=>"+248"],
            ["name"=>"Sierra Leone", "code"=>"SL", "phonecode"=>"+232"],
            ["name"=>"Singapore", "code"=>"SG", "phonecode"=>"+65"],
            ["name"=>"Sint Maarten (Dutch part)", "code"=>"SX", "phonecode"=>"+1"],
            ["name"=>"Slovakia", "code"=>"SK", "phonecode"=>"+421"],
            ["name"=>"Slovenia", "code"=>"SI", "phonecode"=>"+386"],
            ["name"=>"Solomon Islands", "code"=>"SB", "phonecode"=>"+677"],
            ["name"=>"Somalia", "code"=>"SO", "phonecode"=>"+252"],
            ["name"=>"South Africa", "code"=>"ZA", "phonecode"=>"+27"],
            ["name"=>"South Georgia and the South Sandwich Islands", "code"=>"GS", "phonecode"=>"+0"],
            ["name"=>"South Sudan", "code"=>"SS", "phonecode"=>"+211"],
            ["name"=>"Spain", "code"=>"ES", "phonecode"=>"+34"],
            ["name"=>"Sri Lanka", "code"=>"LK", "phonecode"=>"+94"],
            ["name"=>"Sudan", "code"=>"SD", "phonecode"=>"+249"],
            ["name"=>"Suriname", "code"=>"SR", "phonecode"=>"+597"],
            ["name"=>"Svalbard and Jan Mayen", "code"=>"SJ", "phonecode"=>"+47"],
            ["name"=>"Swaziland", "code"=>"SZ", "phonecode"=>"+268"],
            ["name"=>"Sweden", "code"=>"SE", "phonecode"=>"+46"],
            ["name"=>"Switzerland", "code"=>"CH", "phonecode"=>"+41"],
            ["name"=>"Syrian Arab Republic", "code"=>"SY", "phonecode"=>"+963"],
            ["name"=>"Taiwan", "code"=>"TW", "phonecode"=>"+886"],
            ["name"=>"Tajikistan", "code"=>"TJ", "phonecode"=>"+992"],
            ["name"=>"Tanzania, United Republic of", "code"=>"TZ", "phonecode"=>"+255"],
            ["name"=>"Thailand", "code"=>"TH", "phonecode"=>"+66"],
            ["name"=>"Timor-Leste", "code"=>"TL", "phonecode"=>"+670"],
            ["name"=>"Togo", "code"=>"TG", "phonecode"=>"+228"],
            ["name"=>"Tokelau", "code"=>"TK", "phonecode"=>"+690"],
            ["name"=>"Tonga", "code"=>"TO", "phonecode"=>"+676"],
            ["name"=>"Trinidad and Tobago", "code"=>"TT", "phonecode"=>"+1868"],
            ["name"=>"Tunisia", "code"=>"TN", "phonecode"=>"+216"],
            ["name"=>"Turkey", "code"=>"TR", "phonecode"=>"+90"],
            ["name"=>"Turkmenistan", "code"=>"TM", "phonecode"=>"+993"],
            ["name"=>"Turks and Caicos Islands", "code"=>"TC", "phonecode"=>"+1649"],
            ["name"=>"Tuvalu", "code"=>"TV", "phonecode"=>"+688"],
            ["name"=>"Uganda", "code"=>"UG", "phonecode"=>"+256"],
            ["name"=>"Ukraine", "code"=>"UA", "phonecode"=>"+380"],
            ["name"=>"United Arab Emirates", "code"=>"AE", "phonecode"=>"+971"],
            ["name"=>"United Kingdom", "code"=>"GB", "phonecode"=>"+44"],
            ["name"=>"United States", "code"=>"US", "phonecode"=>"+1"],
            ["name"=>"United States Minor Outlying Islands", "code"=>"UM", "phonecode"=>"+1"],
            ["name"=>"Uruguay", "code"=>"UY", "phonecode"=>"+598"],
            ["name"=>"Uzbekistan", "code"=>"UZ", "phonecode"=>"+998"],
            ["name"=>"Vanuatu", "code"=>"VU", "phonecode"=>"+678"],
            ["name"=>"Venezuela, Bolivarian Republic of", "code"=>"VE", "phonecode"=>"+58"],
            ["name"=>"Viet Nam", "code"=>"VN", "phonecode"=>"+84"],
            ["name"=>"Virgin Islands, British", "code"=>"VG", "phonecode"=>"+1284"],
            ["name"=>"Virgin Islands, U.S.", "code"=>"VI", "phonecode"=>"+1340"],
            ["name"=>"Wallis and Futuna", "code"=>"WF", "phonecode"=>"+681"],
            ["name"=>"Western Sahara", "code"=>"EH", "phonecode"=>"+212"],
            ["name"=>"Yemen", "code"=>"YE", "phonecode"=>"+967"],
            ["name"=>"Zambia", "code"=>"ZM", "phonecode"=>"+260"],
            ["name"=>"Zimbabwe", "code"=>"ZW", "phonecode"=>"+263"]
        ];      

        if(count($countries) > 0) {
            foreach($countries as $country)
            {
                if(!(Country::where('code',$country['code'])->exists())) {        
                    Country::create($country);
                }else{
                    Country::where('code',$country['code'])->update(['phonecode' => $country['phonecode']]);
                }      
            }
        }
    }
}
